### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by perun-01** [TheSTL/Visualize-Sorting-Algorithm#3]
The below mentioned missing dependency is leading to the TypeError [ERR_INVALID_ARG_TYPE]
error. 
So "react-dev-utils": "^10.0.0"(Add this to package.json) file.

**Comment by TheSTL** [comment]
can you add a screenshot or more details like how you face this issue? @perun-01

**Comment by perun-01** [comment]
> can you add a screenshot or more details like how you face this issue? @perun-01
*STACKTRACE*
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at noopServiceWorkerMiddleware (/workspace/REDACTED/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/workspace/REDACTED/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/workspace/REDACTED/node_modules/express/lib/router/index.js:317:13)
    at /workspace/REDACTED/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/workspace/REDACTED/node_modules/express/lib/router/index.js:335:12)
    at next (/workspace/REDACTED/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/workspace/REDACTED/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/workspace/REDACTED/node_modules/express/lib/router/layer.js:95:5)


Also, for more info ..u can check this link : https://github.com/facebook/create-react-app/issues/8499

**Comment by TheSTL** [comment]
closing this issue because  PR: [#4 ] fixed it
